apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: redis
spec:
  containers:
    - name: redis
      image: absolootly/docker-redis
      ports:
        - containerPort: 6379
          protocol: TCP
      volumeMounts:
        - mountPath: /var/lib/redis
          name: data
  volumes:
    - name: data
      emptyDir: {}
